language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- ./mvnw clean install -pl spring-boot-docs -Pdefault,full
script:
- mvn test -B