language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn clean verify -Dgpg.skip=true
script:
- mvn test -B